eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
currentEnvValue: "Development environment of Department"
management:
  endpoints:
    web:
      exposure:
        include: health,info  # Ensure this includes health and info endpoints
  endpoint:
    health:
      show-details: always
