eureka:
   client:
      serviceUrl:
         defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
currentEnvValue: "default environment of Department"
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers, retries, rate-limiters, bulkheads, time-limiters
  endpoint:
    health:
      show-details: always

